### ISSUE TITLE
F′ Proves Flight Readiness Plan for Pleiades 5

### ISSUE THREAD

**Issue by nateinaction** [proveskit/fprime-proves#15]
With an April/May launch time frame we think the last time that we will be able to upload software to the Pleiades satellites will be in Feb/March. To hit this window `fprime-proves` needs to:

- [ ] Investigate if OTA updates are possible maybe using an RTOS like Zephr or FreeRTOS
- [x] #27
- [ ] Get the radio working using Radiolib
- [ ] #28
- [ ] Get the CAN transceiver working for board-to-board communication with the battery board (Best for CalPoly/Alex)
- [ ] Get the SD card working so we can store mission data
- [ ] Get the I2C multiplexer (TCA9456) working so we can communicate with the sensors
    - [ ] Temp sensor first - I2C
    - [ ] Ambient light sensors - I2C
    - [ ] Send commands to the embedded motor drivers for magentorquers - I2C
    - [ ] IMU 6-deg freedom acceleromter/gyro - I2C
    - [ ] IMU 6-deg freedom magnetometer - I2C
- [ ] Add attitude control and determination algorithm (CalPoly is working on this)
-  [ ] #16
    - [ ] We need to be able to set the time
    - [ ] We need to be able to read the time
    - [ ] We need to be able to set alarms that will toggle a GPIO pin
    - [ ] We need to be able to activate trickle charge

**Comment by Mikefly123** [comment]
Hey Nate, finally just circling back to this now! This looks like a pretty good list of tasks to me, I will start breaking them out into their own issues.
