### ISSUE TITLE
V1.0 Manger Components

### ISSUE THREAD

**Issue by Mikefly123** [proveskit/fprime-proves#40]
# What is Required
Once the sensor components are created we will need manager components to take the data from them to actually perform tasks!

# Required Managers

- [ ] Satellite Health Manager 
- [ ] Satellite Thermal Manager
- [ ] Satellite Power Manager
- [ ] Satellite Communications Manager
- [ ] Mission Scheduling Manager
- [ ] #41
